name: CI/CD Cinéphoria

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Exécution des tests PHP
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.2
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lc_cinephoria
          MYSQL_USER: lamine
          MYSQL_PASSWORD: Root1234!!
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=5

      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
        options: --health-cmd "mongosh --eval 'db.runCommand({ ping: 1 })'" --health-interval=10s --health-timeout=5s --health-retries=5


    steps:
      - name: Checkout du code 
        uses: actions/checkout@v3

      - name: Configuration de PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: pdo_mysql, mysqli, mbstring, zip, pcntl, bcmath, gd, mongodb
          coverage: none

      - name: Cache Composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: composer-

      - name: Installation des dépendances PHP
        run: composer install --no-interaction --prefer-dist

      - name: Exécution des tests PHPUnit
        run: vendor/bin/phpunit tests

  build:
    name: Construction de l image Docker
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Connexion à Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construction et push de l image Docker
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/cinephoria-web:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/cinephoria-web:latest

  deploy:
    name: Déploiement sur le VPS PlanetHoster
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Déploiement sur VPS PlanetHoster
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /var/www/html/cinephoria
          docker pull ${{ secrets.DOCKER_USERNAME }}/cinephoria-web:latest
          docker stop cinephoria_web || true
          docker rm cinephoria_web || true
          docker run -d --name cinephoria_web --network=cinephoria_network -p 80:80 ${{ secrets.DOCKER_USERNAME }}/cinephoria-web:latest
          EOF
